name: Check roles

on:
  push: # To be changed: pull-request
    branches:
      - 'test' # To be changed: main


env:
  orch-project: sn-pj-iam-management

jobs:
  create_pr_repo_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Create PR
        uses: funivan/github-autopr@0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

